language: node_js
node_js:
- '0.10'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g grunt-cli
- npm install -g bower
- bower install
- gem install jekyll
- jekyll serve --detach
- sleep 3
script:
- grunt all
after_success:
- chmod +x ./deploy-ghpages.sh
- "./deploy-ghpages.sh"
env:
  global:
    secure: hyDT3LnMBLFyWxBhOgmL0jpSEKVggNC/10PpVb3ANa3QhSCHD5m6pzabobXVHaamHcKM3yTXVDTnmoUW2jHhR5mwFi1CmL0ul9iqLA7TjHBwk6y0pLA/29TgKcWQHopggk4uHumvTwiSkyATQbHUBbGKWuXNP7xgr2JZetEnv0g=
